language: java

before_script:
 - cd adlib_dbunit_mongo

after_failure:
- wget -O - https://unitcover.herokuapp.com/scripts/upload.sh | bash /dev/stdin pussinboots dbunit-mongodb "."

after_success:
- wget -O - https://unitcover.herokuapp.com/scripts/upload.sh | bash /dev/stdin pussinboots dbunit-mongodb "."
